# Generated by Django 5.0.7 on 2025-09-29 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания (если есть)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активное занятие'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Повторяющееся занятие'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата начала действия расписания'),
        ),
    ]
