# Generated by Django 5.0.7 on 2025-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedule_end_date_schedule_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='lesson_date',
            field=models.DateField(blank=True, help_text='Конкретная дата занятия', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('client', 'schedule', 'lesson_date')},
        ),
    ]
