# Generated by Django 5.2.6 on 2025-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedule_end_date_schedule_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_date',
            field=models.DateField(blank=True, help_text='Фактическая дата занятия', null=True),
        ),
    ]
