# Generated by Django 5.2.6 on 2025-10-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_unique_together_booking_lesson_date_and_more'),
        ('main', '0003_booking_class_date'),
    ]

    operations = [
    ]
