# Generated by Django 5.2.6 on 2025-10-05 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20251006_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('client', 'schedule')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата проведения занятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], editable=False),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lesson_date',
        ),
    ]
