# Generated by Django 5.2.6 on 2025-10-05 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_schedule_options_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата проведения занятия'),
        ),
    ]
