# Generated by Django 5.2.6 on 2025-10-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(help_text='Дата проведения занятия'),
        ),
    ]
